from django.urls import path

from . import opengraph, public, storage, views

urlpatterns = [
    path("", views.welcome),
    path("up", public.health),
    path("first_run", views.first_run),
    path("session/new", views.session),
    path("session", views.session),
    path("session/transfers/<str:id>", views.transfer),
    path("join/<str:code>", views.join),
    path("rooms", views.room),
    path("rooms/<int:id>", views.room),
    path("rooms/<int:id>/@<int:message_id>", views.room),
    path("rooms/<int:room_id>/messages", views.messages),
    path("rooms/<int:room_id>/messages/<int:id>", views.messages),
    path("rooms/<int:room_id>/messages/<int:id>/edit", views.messages, {"edit": True}),
    path("messages/<int:id>", views.messages),
    path("messages/<int:id>/edit", views.messages, {"edit": True}),
    path("rooms/<int:room_id>/<str:bot_key>/messages", views.messages),
    path("rooms/<int:room_id>/<str:bot_key>/messages/<int:id>", views.messages),
    path(
        "rooms/<int:room_id>/<str:bot_key>/messages/<int:message_id>/boosts",
        views.bot_boosts,
    ),
    path(
        "rooms/<int:room_id>/<str:bot_key>/messages/<int:message_id>/boosts/<int:id>",
        views.bot_boosts,
    ),
    path("rooms/<int:room_id>/refresh", views.refresh),
    path("rooms/<int:room_id>/involvement", views.involvement),
    path("rooms/<int:room_id>/settings", views.involvement),
    path("rooms/<str:kind>/new", views.room_form, {"new": True}),
    path("rooms/<str:kind>/<int:id>/edit", views.room_form, {"edit": True}),
    path("rooms/<str:kind>/<int:id>", views.room_form),
    path("rooms/<str:kind>", views.room_form),
    path("messages/<int:message_id>/boosts", views.boosts),
    path("messages/<int:message_id>/boosts/new", views.boosts, {"new": True}),
    path("messages/<int:message_id>/boosts/<int:id>", views.boosts),
    path("users/me/sidebar", views.sidebar),
    path("users/<str:id>/sidebar", views.sidebar),
    path("users/me/profile", views.profile),
    path("users/<str:id>/profile", views.profile),
    path("users/<str:user_id>/avatar", public.avatar),
    path("users/<int:user_id>/ban", views.ban),
    path("users/<int:id>", views.user_show),
    path("autocompletable/users", views.autocomplete),
    path("users/me/push_subscriptions", views.push_subscriptions),
    path("users/me/push_subscriptions/<int:id>", views.push_subscriptions),
    path(
        "users/me/push_subscriptions/<int:id>/test_notifications",
        views.push_subscriptions,
        {"test": True},
    ),
    path("account", views.account),
    path("account/edit", views.account),
    path("account/users", views.account_users),
    path("account/users/<int:id>", views.account_users),
    path("account/bots", views.bots),
    path("account/bots/new", views.bots, {"new": True}),
    path("account/bots/<int:id>/edit", views.bots, {"edit": True}),
    path("account/bots/<int:id>/key", views.bots, {"key": True}),
    path("account/bots/<int:id>", views.bots),
    path("account/custom_styles", views.custom_styles),
    path("account/custom_styles/edit", views.custom_styles),
    path("account/logo", public.logo),
    path("account/join_code", views.join_code),
    path("searches", views.searches),
    path("searches/clear", views.searches),
    path("rails/active_storage/direct_uploads", storage.direct_upload),
    path("rails/active_storage/disk/<str:token>", storage.disk),
    path(
        "rails/active_storage/blobs/redirect/<str:token>/<str:filename>",
        storage.blob_redirect,
    ),
    path(
        "rails/active_storage/blobs/proxy/<str:token>/<str:filename>",
        storage.blob_redirect,
    ),
    path(
        "rails/active_storage/representations/redirect/<str:token>/<str:variation>/<str:filename>",
        storage.representation,
    ),
    path(
        "rails/active_storage/representations/proxy/<str:token>/<str:variation>/<str:filename>",
        storage.representation,
    ),
    path("unfurl_link", opengraph.unfurl),
    path("webmanifest", public.manifest),
    path("webmanifest.json", public.manifest),
    path("service-worker", public.service_worker),
    path("service-worker.js", public.service_worker),
    path("qr_code/<str:id>", public.qr),
    path("<path:path>", public.static),
]
